wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722685994
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 22
      - 23
      - 35
      4: 3.10.14
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 2
policy_kwargs:
  desc: null
  value: '{''features_extractor_class'': <class ''games.model.policy.CustomHeteroGNN''>,
    ''features_extractor_kwargs'': {''features_dim'': 64, ''hidden_size'': 64, ''num_layer'':
    2, ''obj_type_id'': ''obj'', ''arity_dict'': {''ChickenOnLane'': 2, ''CarOnLane'':
    2, ''LaneNextToLane'': 2, ''LaneNearPlayer'': 2}, ''game'': ''freeway''}}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1722685999859753000
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: None
_last_obs:
  desc: null
  value: "[[[103. 145.   0.   0.   1.   0.   0.]\n  [105.  50.   0.   0.   0.   1.\
    \   0.]\n  [105.  80.   0.   0.   0.   1.   0.]\n  [130.  80.   2.   0.   0. \
    \  0.   1.]\n  [ 77.  80.   2.   0.   0.   0.   1.]\n  [149.  80.   1.   0.  \
    \ 0.   0.   1.]\n  [ 72.  50.   1.   0.   0.   0.   1.]\n  [158.  50.   2.   0.\
    \   0.   0.   1.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n  [  0.   0.   0. \
    \  0.   0.   0.   0.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n  [  0.   0.  \
    \ 0.   0.   0.   0.   0.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n  [  0.   0.\
    \   0.   0.   0.   0.   0.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n  [  0. \
    \  0.   0.   0.   0.   0.   0.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n  [ \
    \ 0.   0.   0.   0.   0.   0.   0.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n\
    \  [  0.   0.   0.   0.   0.   0.   0.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n\
    \  [  0.   0.   0.   0.   0.   0.   0.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n\
    \  [  0.   0.   0.   0.   0.   0.   0.]]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x104d01420>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (24, 7), float32)
action_space:
  desc: null
  value: Discrete(3)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x2a66e1ab0>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x2a66f8dc0>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x2a665ac20>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): CustomHeteroGNN(\n    (model):\
    \ HeteroGAT(\n      (layers): ModuleList(\n        (0): ModuleDict(\n        \
    \  (obj): GATConv(7, 64, heads=1)\n        )\n        (1): ModuleDict(\n     \
    \     (obj): GATConv(64, 64, heads=1)\n        )\n      )\n      (global_pool):\
    \ GlobalAttention(gate_nn=Sequential(\n        (0): Linear(in_features=64, out_features=64,\
    \ bias=True)\n        (1): ReLU()\n        (2): Linear(in_features=64, out_features=1,\
    \ bias=True)\n      ), nn=None)\n    )\n  )\n  (pi_features_extractor): CustomHeteroGNN(\n\
    \    (model): HeteroGAT(\n      (layers): ModuleList(\n        (0): ModuleDict(\n\
    \          (obj): GATConv(7, 64, heads=1)\n        )\n        (1): ModuleDict(\n\
    \          (obj): GATConv(64, 64, heads=1)\n        )\n      )\n      (global_pool):\
    \ GlobalAttention(gate_nn=Sequential(\n        (0): Linear(in_features=64, out_features=64,\
    \ bias=True)\n        (1): ReLU()\n        (2): Linear(in_features=64, out_features=1,\
    \ bias=True)\n      ), nn=None)\n    )\n  )\n  (vf_features_extractor): CustomHeteroGNN(\n\
    \    (model): HeteroGAT(\n      (layers): ModuleList(\n        (0): ModuleDict(\n\
    \          (obj): GATConv(7, 64, heads=1)\n        )\n        (1): ModuleDict(\n\
    \          (obj): GATConv(64, 64, heads=1)\n        )\n      )\n      (global_pool):\
    \ GlobalAttention(gate_nn=Sequential(\n        (0): Linear(in_features=64, out_features=64,\
    \ bias=True)\n        (1): ReLU()\n        (2): Linear(in_features=64, out_features=1,\
    \ bias=True)\n      ), nn=None)\n    )\n  )\n  (mlp_extractor): MlpExtractor(\n\
    \    (policy_net): Sequential(\n      (0): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n      (0):\
    \ Linear(in_features=64, out_features=64, bias=True)\n      (1): Tanh()\n    \
    \  (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=3, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x2a665bfd0>
