wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720903424
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 22
      - 23
      - 35
      4: 3.10.14
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 2
policy_kwargs:
  desc: null
  value: '{''features_extractor_class'': <class ''games.model.policy.CustomHeteroGNN''>,
    ''features_extractor_kwargs'': {''features_dim'': 64, ''hidden_size'': 64, ''num_layer'':
    2, ''obj_type_id'': ''obj'', ''arity_dict'': {''ChickenOnLane'': 2, ''CarOnLane'':
    2, ''LaneNextToLane'': 2}, ''game'': ''freeway''}}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1720903432612251754
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: None
_last_obs:
  desc: null
  value: "[[[103. 145.   0.   0.   1.   0.   0.]\n  [105.  80.   0.   0.   0.   1.\
    \   0.]\n  [105. 120.   0.   0.   0.   1.   0.]\n  [ 66. 120.   1.   0.   0. \
    \  0.   1.]\n  [103. 120.   1.   0.   0.   0.   1.]\n  [122. 120.   1.   0.  \
    \ 0.   0.   1.]\n  [149.  80.   1.   0.   0.   0.   1.]\n  [129.  80.   1.   0.\
    \   0.   0.   1.]\n  [ 72.  80.   1.   0.   0.   0.   1.]\n  [ 24. 120.   1. \
    \  0.   0.   0.   1.]\n  [136.  80.   1.   0.   0.   0.   1.]\n  [ 79.  80.  \
    \ 1.   0.   0.   0.   1.]\n  [186.  80.   1.   0.   0.   0.   1.]\n  [175. 120.\
    \   1.   0.   0.   0.   1.]\n  [120.  80.   1.   0.   0.   0.   1.]\n  [ 90. 120.\
    \   1.   0.   0.   0.   1.]\n  [ 80.  80.   1.   0.   0.   0.   1.]\n  [141. 120.\
    \   1.   0.   0.   0.   1.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n  [  0. \
    \  0.   0.   0.   0.   0.   0.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n  [ \
    \ 0.   0.   0.   0.   0.   0.   0.]\n  [  0.   0.   0.   0.   0.   0.   0.]\n\
    \  [  0.   0.   0.   0.   0.   0.   0.]]\n\n [[103. 145.   0.   0.   1.   0. \
    \  0.]\n  [105.  50.   0.   0.   0.   1.   0.]\n  [105.  80.   0.   0.   0.  \
    \ 1.   0.]\n  [ 65.  50.   1.   0.   0.   0.   1.]\n  [126.  80.   1.   0.   0.\
    \   0.   1.]\n  [120.  80.   1.   0.   0.   0.   1.]\n  [ 53.  50.   1.   0. \
    \  0.   0.   1.]\n  [124.  50.   1.   0.   0.   0.   1.]\n  [ 99.  80.   1.  \
    \ 0.   0.   0.   1.]\n  [155.  50.   1.   0.   0.   0.   1.]\n  [178.  80.   1.\
    \   0.   0.   0.   1.]\n  [ 68.  50.   1.   0.   0.   0.   1.]\n  [151.  50. \
    \  1.   0.   0.   0.   1.]\n  [ 81.  50.   1.   0.   0.   0.   1.]\n  [  5.  50.\
    \   1.   0.   0.   0.   1.]\n  [166.  50.   1.   0.   0.   0.   1.]\n  [ 97. \
    \ 50.   1.   0.   0.   0.   1.]\n  [108.  50.   1.   0.   0.   0.   1.]\n  [135.\
    \  50.   1.   0.   0.   0.   1.]\n  [112.  80.   1.   0.   0.   0.   1.]\n  [141.\
    \  50.   1.   0.   0.   0.   1.]\n  [ 88.  50.   1.   0.   0.   0.   1.]\n  [173.\
    \  50.   1.   0.   0.   0.   1.]\n  [  0.   0.   0.   0.   0.   0.   0.]]]"
_last_episode_starts:
  desc: null
  value: '[ True  True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at
    0x7fcdbb0fe200>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (24, 7), float32)
action_space:
  desc: null
  value: Discrete(3)
n_envs:
  desc: null
  value: 2
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x7fcdbafaab90>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x7fcdba613eb0>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7fcdbaf9ff70>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): CustomHeteroGNN(\n    (model):\
    \ HeteroGNN(\n      (encoding_mlps): ModuleDict(\n        (obj): MLP(7, 64, 64)\n\
    \        (ChickenOnLane): MLP(14, 128, 128)\n        (CarOnLane): MLP(14, 128,\
    \ 128)\n        (LaneNextToLane): MLP(14, 128, 128)\n      )\n      (obj_to_atom):\
    \ FanOutMP(\n        (update_mlp_by_dst): ModuleDict(\n          (ChickenOnLane):\
    \ MLP(128, 128, 128)\n          (CarOnLane): MLP(128, 128, 128)\n          (LaneNextToLane):\
    \ MLP(128, 128, 128)\n        )\n        (simple): SimpleConv()\n      )\n   \
    \   (obj_update): MLP(128, 128, 64)\n      (atom_to_obj): FanInMP(\n        (select):\
    \ SelectMP()\n      )\n    )\n  )\n  (pi_features_extractor): CustomHeteroGNN(\n\
    \    (model): HeteroGNN(\n      (encoding_mlps): ModuleDict(\n        (obj): MLP(7,\
    \ 64, 64)\n        (ChickenOnLane): MLP(14, 128, 128)\n        (CarOnLane): MLP(14,\
    \ 128, 128)\n        (LaneNextToLane): MLP(14, 128, 128)\n      )\n      (obj_to_atom):\
    \ FanOutMP(\n        (update_mlp_by_dst): ModuleDict(\n          (ChickenOnLane):\
    \ MLP(128, 128, 128)\n          (CarOnLane): MLP(128, 128, 128)\n          (LaneNextToLane):\
    \ MLP(128, 128, 128)\n        )\n        (simple): SimpleConv()\n      )\n   \
    \   (obj_update): MLP(128, 128, 64)\n      (atom_to_obj): FanInMP(\n        (select):\
    \ SelectMP()\n      )\n    )\n  )\n  (vf_features_extractor): CustomHeteroGNN(\n\
    \    (model): HeteroGNN(\n      (encoding_mlps): ModuleDict(\n        (obj): MLP(7,\
    \ 64, 64)\n        (ChickenOnLane): MLP(14, 128, 128)\n        (CarOnLane): MLP(14,\
    \ 128, 128)\n        (LaneNextToLane): MLP(14, 128, 128)\n      )\n      (obj_to_atom):\
    \ FanOutMP(\n        (update_mlp_by_dst): ModuleDict(\n          (ChickenOnLane):\
    \ MLP(128, 128, 128)\n          (CarOnLane): MLP(128, 128, 128)\n          (LaneNextToLane):\
    \ MLP(128, 128, 128)\n        )\n        (simple): SimpleConv()\n      )\n   \
    \   (obj_update): MLP(128, 128, 64)\n      (atom_to_obj): FanInMP(\n        (select):\
    \ SelectMP()\n      )\n    )\n  )\n  (mlp_extractor): MlpExtractor(\n    (policy_net):\
    \ Sequential(\n      (0): Linear(in_features=64, out_features=64, bias=True)\n\
    \      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64, bias=True)\n\
    \      (3): Tanh()\n    )\n    (value_net): Sequential(\n      (0): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n  )\n  (action_net):\
    \ Linear(in_features=64, out_features=3, bias=True)\n  (value_net): Linear(in_features=64,\
    \ out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fcdb8aa6c20>
