wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720422948
    t:
      1:
      - 1
      - 55
      - 77
      2:
      - 1
      - 55
      - 77
      3:
      - 22
      - 23
      - 24
      - 34
      - 35
      4: 3.10.14
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 2
policy_kwargs:
  desc: null
  value: '{''features_extractor_class'': <class ''games.model.policy.CustomHeteroGNN''>,
    ''features_extractor_kwargs'': {''features_dim'': 64, ''hidden_size'': 64, ''num_layer'':
    2, ''obj_type_id'': ''obj'', ''arity_dict'': {''atom'': 2}, ''game'': ''pong''}}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1720422961245845938
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: ./logs
_last_obs:
  desc: null
  value: "[[[103.          78.          -3.13404      2.4855165    1.\n     0.   \
    \        0.        ]\n  [ 20.          70.           0.           0.         \
    \  0.\n     1.           0.        ]\n  [185.          70.           0.      \
    \     0.           0.\n     1.           0.        ]]\n\n [[103.          78.\
    \           3.4107127   -2.0897462    1.\n     0.           0.        ]\n  [ 20.\
    \          70.           0.           0.           0.\n     1.           0.  \
    \      ]\n  [185.          70.           0.           0.           0.\n     1.\
    \           0.        ]]\n\n [[103.          78.          -3.9583926   -0.57543737\
    \   1.\n     0.           0.        ]\n  [ 20.          70.           0.     \
    \      0.           0.\n     1.           0.        ]\n  [185.          70.  \
    \         0.           0.           0.\n     1.           0.        ]]\n\n [[103.\
    \          78.          -3.3201158    2.2308812    1.\n     0.           0.  \
    \      ]\n  [ 20.          70.           0.           0.           0.\n     1.\
    \           0.        ]\n  [185.          70.           0.           0.      \
    \     0.\n     1.           0.        ]]]"
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at
    0x76aef12d3940>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (3, 7), float32)
action_space:
  desc: null
  value: Discrete(3)
n_envs:
  desc: null
  value: 4
n_steps:
  desc: null
  value: 2048
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
ent_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x76aef0801b40>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x76aef0854a60>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x76aef11219c0>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): CustomHeteroGNN(\n    (model):\
    \ HeteroGNN(\n      (encoding_mlps): ModuleDict(\n        (obj): MLP(7, 64, 64)\n\
    \        (atom): MLP(14, 128, 128)\n      )\n      (obj_to_atom): FanOutMP(\n\
    \        (update_mlp_by_dst): ModuleDict(\n          (atom): MLP(128, 128, 128)\n\
    \        )\n        (simple): SimpleConv()\n      )\n      (obj_update): MLP(128,\
    \ 128, 64)\n      (atom_to_obj): FanInMP(\n        (select): SelectMP()\n    \
    \  )\n    )\n  )\n  (pi_features_extractor): CustomHeteroGNN(\n    (model): HeteroGNN(\n\
    \      (encoding_mlps): ModuleDict(\n        (obj): MLP(7, 64, 64)\n        (atom):\
    \ MLP(14, 128, 128)\n      )\n      (obj_to_atom): FanOutMP(\n        (update_mlp_by_dst):\
    \ ModuleDict(\n          (atom): MLP(128, 128, 128)\n        )\n        (simple):\
    \ SimpleConv()\n      )\n      (obj_update): MLP(128, 128, 64)\n      (atom_to_obj):\
    \ FanInMP(\n        (select): SelectMP()\n      )\n    )\n  )\n  (vf_features_extractor):\
    \ CustomHeteroGNN(\n    (model): HeteroGNN(\n      (encoding_mlps): ModuleDict(\n\
    \        (obj): MLP(7, 64, 64)\n        (atom): MLP(14, 128, 128)\n      )\n \
    \     (obj_to_atom): FanOutMP(\n        (update_mlp_by_dst): ModuleDict(\n   \
    \       (atom): MLP(128, 128, 128)\n        )\n        (simple): SimpleConv()\n\
    \      )\n      (obj_update): MLP(128, 128, 64)\n      (atom_to_obj): FanInMP(\n\
    \        (select): SelectMP()\n      )\n    )\n  )\n  (mlp_extractor): MlpExtractor(\n\
    \    (policy_net): Sequential(\n      (0): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64,\
    \ bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n      (0):\
    \ Linear(in_features=64, out_features=64, bias=True)\n      (1): Tanh()\n    \
    \  (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=3, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x76aef08afa90>
